export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCT = 'GET_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCTS = "DELETE_PRODUCTS";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
